
version: '3.4'

services:
  monitoring:
    image: monitoring
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    links:
      - fluent-bit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24225
        tag: monitoring.access

  fluent-bit:
    image: fluent/fluent-bit:1.7
    volumes:
      - ./fluent-bit/conf/fluentBit.conf:/fluent-bit/etc/fluentBit.conf
    depends_on:
      - fluentd
    ports:
      - "24225:24225"
      - "24225:24225/udp"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: monitoringViaFluentBit.access

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.10.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
