
version: '3.4'

services:
  monitoring:
    image: monitoring
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - fluent-bit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: monitoring.access
  fluent-bit:
    image: fluent/fluent-bit:1.7
    container_name: "fluent-bit"
    volumes:
      - ./fluent-bit/conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
